# -*- coding: utf-8 -*-
"""workshop-1-day-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FM6WgG_MH8Xu41zCqnM0H8CjLc_RcpiX
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

df = pd.read_csv("Teen_Mental_Health_Dataset.csv")

print("="*60)
print("FIRST FIVE RECORDS")
print("="*60)

print(df.head())

print("\n")
print("="*60)
print("DATASET INFORMATION")
print("="*60)

print(df.info())

print("\n")
print("="*60)
print("STATISTICAL SUMMARY")
print("="*60)

print(df.describe())

print("\n")
print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

print("\n")
print("="*60)
print("DUPLICATES")
print("="*60)

print(df.duplicated().sum())

df = df.drop("social_interaction_level", axis=1)

print("\n")
print("="*60)
print("TARGET CLASSES")
print("="*60)

print(df["age"].value_counts())

encoder = LabelEncoder()

df["anxiety_level"] = encoder.fit_transform(df["anxiety_level"])

print("\nEncoded Classes")

for i, name in enumerate(encoder.classes_):
    print(i, "=", name)

X = df.drop("anxiety_level", axis=1)
y = df["anxiety_level"]

X = pd.get_dummies(X, columns=['gender', 'platform_usage'], drop_first=True)

print('\n')
print('='*60)
print('X after One-Hot Encoding')
print('='*60)
print(X.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Samples :", len(X_train))
print("Testing Samples :", len(X_test))

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=500)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("\n")
print("="*60)
print("MODEL ACCURACY")
print("="*60)

print(f"Accuracy : {accuracy*100:.2f}%")

print("\n")
print("="*60)
print("CLASSIFICATION REPORT")
print("="*60)

print(classification_report(
    y_test,
    y_pred,
    target_names=[str(c) for c in encoder.classes_]
))

cm = confusion_matrix(y_test, y_pred)

print("\n")
print("="*60)
print("CONFUSION MATRIX")
print("="*60)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=encoder.classes_
)

disp.plot(cmap="Blues")

plt.title("Confusion Matrix")

plt.show()

importance = np.mean(np.abs(model.coef_), axis=0)

feature_names = X_train.columns

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importance
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print("\n")
print("="*60)
print("FEATURE IMPORTANCE")
print("="*60)

print(importance_df)

plt.figure(figsize=(8,5))

plt.bar(
    importance_df["Feature"],
    importance_df["Importance"]
)

plt.title("Feature Importance")

plt.xlabel("Features")

plt.ylabel("Importance")

plt.xticks(rotation=20)

plt.show()

print("\n")
print("="*60)
print("NEW TEEN ANXIETY LEVEL PREDICTION")
print("="*60)
new_customer_data = [[16, 1, 4.5, 0, 7.0, 1.5, 3.0, 5, 3, 0]]
new_customer_df = pd.DataFrame(new_customer_data, columns=X_train.columns)
prediction = model.predict(new_customer_df)

predicted_anxiety_level = encoder.inverse_transform(prediction)

print("Predicted Anxiety Level :", predicted_anxiety_level[0])

multiple_teen_data = [
    [15, 0, 3.0, 1, 8.0, 1.0, 3.5, 4, 2, 0],
    [17, 1, 7.0, 2, 6.0, 2.5, 2.8, 8, 7, 1],
    [14, 0, 5.5, 0, 7.5, 2.0, 3.9, 6, 4, 0]
]

multiple_teen_df = pd.DataFrame(multiple_teen_data, columns=X_train.columns)

predictions = model.predict(multiple_teen_df)

species = encoder.inverse_transform(predictions)

print("\nMultiple Predictions")

for i in range(len(multiple_teen_data)):
    print(f"Teen {i+1} predicted anxiety level --> {species[i]}")

import joblib

joblib.dump(model, "iris_model.pkl")

joblib.dump(encoder, "label_encoder.pkl")

print("\nModel Saved Successfully.")

import pandas as pd
import joblib

loaded_model = joblib.load("iris_model.pkl")

loaded_encoder = joblib.load("label_encoder.pkl")


sample_data = [[16, 1, 4.5, 0, 7.0, 1.5, 3.0, 5, 3, 0]]
sample_df = pd.DataFrame(sample_data, columns=['age', 'gender', 'daily_social_media_hours', 'platform_usage', 'sleep_hours', 'screen_time_before_sleep', 'academic_performance', 'stress_level', 'addiction_level', 'depression_label'])

pred = loaded_model.predict(sample_df)

species = loaded_encoder.inverse_transform(pred)

print("\nPrediction Using Saved Model")

print(species[0])