# -*- coding: utf-8 -*-
"""workshop-2-day-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XL0PyL586XbOGOIdER9wlLfrUt2GR8co
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

print("="*60)
print("Libraries Imported Successfully")
print("="*60)

import pandas as pd

df = pd.read_csv("fifa_world_cup_2026_player_performance.csv")
print(df.head())

print("\nFirst Five Rows")
print(df.head())

print("\nDataset Information")
print(df.info())

print("\nShape of Dataset")
print(df.shape)

print("\nColumn Names")
print(df.columns)

print("\nMissing Values")
print(df.isnull().sum())

# If missing values exist, remove them.
df = df.dropna()

print("\nStatistical Summary")
print(df.describe())

X = df[["nationality", "team", "jersey_number"]]

print("\nFeatures")
print(X.head())

y = df["position"]

print("\nTarget Variable")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("\nTraining Data Shape")
print(X_train.shape)

print("\nTesting Data Shape")
print(X_test.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000) # Increased max_iter for convergence

print("\nLogistic Regression Model Created")

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Identify categorical and numerical features
categorical_features = ['nationality', 'team']
numerical_features = ['jersey_number']

# Create a column transformer for one-hot encoding
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('num', 'passthrough', numerical_features)
    ],
    remainder='passthrough' # Keep other columns (if any) as they are
)

# Apply the preprocessing to X_train and X_test
X_train_encoded = preprocessor.fit_transform(X_train)
X_test_encoded = preprocessor.transform(X_test)

# Train the model with the encoded data
model.fit(X_train_encoded, y_train)

print("\nModel Training Completed")

print("\nIntercept")
print(model.intercept_)

print("\nCoefficients")

# Get feature names after one-hot encoding from the preprocessor
feature_names = preprocessor.get_feature_names_out()

# Get the class names (unique positions) from the trained model
class_names = model.classes_

# Create a DataFrame for coefficients
# The rows will represent the different classes (positions) and columns will be the features
coefficients_df = pd.DataFrame(
    model.coef_,
    columns=feature_names,
    index=class_names
)

# Transpose the DataFrame for better readability, showing features as rows and classes as columns
print("Coefficients per feature and class:")
print(coefficients_df.T)

prediction = model.predict(X_test_encoded)

print("\nPrediction Completed")

comparison = pd.DataFrame({
    "Actual Profit": y_test.values,
    "Predicted Profit": prediction
})

print("\nActual vs Predicted")
print(comparison.head(20))

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, prediction)

class_report = classification_report(y_test, prediction)

conf_matrix = confusion_matrix(y_test, prediction)

print("\nMODEL PERFORMANCE")
print("-"*40)

print("Accuracy Score :", accuracy)
print("\nClassification Report :\n", class_report)
print("\nConfusion Matrix :\n", conf_matrix)

import pandas as pd


new_player_data = pd.DataFrame([
    {'nationality': 'Spanish', 'team': 'Spain', 'jersey_number': 5}
])

# Apply the same preprocessing (one-hot encoding) to the new data
new_player_data_encoded = preprocessor.transform(new_player_data)

# Make a prediction using the preprocessed new data
predicted_position = model.predict(new_player_data_encoded)

print("\nPredicted Position for New Player")
print(predicted_position)

plt.figure(figsize=(8,6))

plt.scatter(
    y_test,
    prediction
)

plt.xlabel("Actual Profit")

plt.ylabel("Predicted Profit")

plt.title("Actual Profit vs Predicted Profit")

plt.grid(True)

plt.show()

# Residual plots are not suitable for classification models as they operate on categorical (string) data.
# The model predicts player positions, which are categories, not continuous numerical values.
# Evaluation for classification models should be done using metrics like accuracy, precision, recall, f1-score, and confusion matrices, which have already been calculated and displayed in the previous cells.

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Calculate the mean absolute coefficient for each feature across all classes
mean_abs_coefficients = coefficients_df.abs().mean(axis=0)

# Create a DataFrame for plotting, including both feature names and their aggregated coefficients
feature_importance_data = pd.DataFrame({
    "Feature": mean_abs_coefficients.index,
    "Coefficient": mean_abs_coefficients.values
})

# Sort the features by their coefficient magnitude for better visualization
feature_importance_data = feature_importance_data.sort_values(by="Coefficient", ascending=False)

plt.figure(figsize=(10, 8)) # Adjust figure size for better readability

# Plotting the top N features (e.g., top 20) for clarity using a horizontal bar chart
num_features_to_plot = 20 # You can adjust this number
plt.barh(
    feature_importance_data["Feature"].head(num_features_to_plot),
    feature_importance_data["Coefficient"].head(num_features_to_plot)
)

plt.title("Top Feature Importance (Mean Absolute Coefficient Across Classes)")
plt.xlabel("Mean Absolute Coefficient")
plt.ylabel("Features")
plt.gca().invert_yaxis() # To display the highest importance at the top
plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.show()

print("\n")
print("="*60)
print("SUMMARY")
print("="*60)

print("""
1. Dataset Loaded Successfully

2. Selected Features:
      Sales
      Quantity
      Discount

3. Target Variable:
      Profit

4. Dataset Split:
      80% Training
      20% Testing

5. Linear Regression Model Trained

6. Predictions Generated

7. Model Evaluated using:
      MAE
      MSE
      RMSE
      R2 Score

8. Predicted Profit for New Orders

9. Visualized Model Performance

Machine Learning Workflow Completed Successfully.
""")